services:
  - type: cron
    name: finai24-newsbot-v3-economy
    runtime: python
    schedule: "*/10 * * * *"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python finai24_newsbot.py"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: STRAPI_API_TOKEN
        sync: false
